apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-1
  labels:
    app: multi-pod
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
  - name: c2
    image: nginx
    ports:
    - containerPort: 80
  - name: c3
    image: ubuntu
    command:
    - sleep
    - 3600